apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apex-build
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - services.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - stateful-infra.yaml
  - edge-and-autoscaling.yaml
  - network-and-policies.yaml
  - runtime-workers.yaml
commonLabels:
  app.kubernetes.io/part-of: apex-build-platform
